---
title: "GKVK Top 10 Birders"
author: Karthik Thrikkadeeri
categories:
  - Data
  - R
  - Birding
date: "2022-01-22"
draft: false
excerpt: Grid is the very first CSS module created specifically to solve the layout
  problems we’ve all been hacking our way around for as long as we’ve been making
  websites.
featured: true
layout: single-sidebar
links:
- icon: door-open
  icon_pack: fas
  name: website
  url: https://allisonhorst.github.io/palmerpenguins/
- icon: github
  icon_pack: fab
  name: code
  url: https://github.com/allisonhorst/palmerpenguins/
- icon: newspaper
  icon_pack: far
  name: Blog post
  url: https://education.rstudio.com/blog/2020/07/palmerpenguins-cran/
subtitle: ""
tags:
- hugo-site
editor_options: 
  chunk_output_type: console
---

GKVK leaderboard

```{r setup}

library(tidyverse)
library(lubridate)
library(magrittr)
library(gganimate)
library(gifski)

theme_set(theme_classic())

# # loading data and filtering for GKVK hotspot
# load("content/project/GKVK leaderboard/ebd_IN_relDec-2021.RData")
# 
# data_GKVK <- data %>% 
#   filter(LOCALITY.ID == "L2525709")
# 
# rm(list = setdiff(ls(), "data_GKVK"))
# save.image("content/project/GKVK leaderboard/data_GKVK.RData")

# observer information
eBird.users <- read.delim("content/project/GKVK leaderboard/ebd_users_relDec-2021.txt", 
                          sep = "\t", header = T, quote = "", 
                          stringsAsFactors = F, na.strings = c(""," ",NA))
names(eBird.users) <- c("OBSERVER.ID","FIRST.NAME","LAST.NAME")
eBird.users <- eBird.users %>% transmute(OBSERVER.ID = OBSERVER.ID,
                                         FULL.NAME = paste(FIRST.NAME, LAST.NAME))

```

```{r monthly, eval=FALSE}


load("content/project/GKVK leaderboard/data_GKVK.RData")

data0 <- data_GKVK  %>% 
  mutate(CATEGORY == case_when(CATEGORY == "domestic" & 
                                 COMMON.NAME == "Rock Pigeon" ~ "species",
                               TRUE ~ CATEGORY)) %>% 
  filter(CATEGORY %in% c("issf","species")) %>% 
  select(OBSERVER.ID, OBSERVATION.DATE, YEAR, MONTH, DAY.M, COMMON.NAME) %>% 
  left_join(eBird.users) %>% 
  select(-OBSERVER.ID) %>% 
  arrange(OBSERVATION.DATE, FULL.NAME) %>% 
  filter(FULL.NAME != "MigrantWatch (group account)")

data1 <- data0 %>% 
  group_by(FULL.NAME, COMMON.NAME) %>% 
  slice(1) %>% 
  mutate(YEAR = year(as.Date(OBSERVATION.DATE)),
         MONTH = month(as.Date(OBSERVATION.DATE), label = T),
         YEAR.MONTH = paste(YEAR, MONTH)) %>% 
  arrange(YEAR, MONTH, FULL.NAME)

data2 <- data1 %>% 
  group_by(FULL.NAME) %>% 
  mutate(SP.NO = seq(n())) %>% 
  group_by(FULL.NAME, YEAR, MONTH) %>% 
  summarise(SP.NO = max(SP.NO))

data3 <- data2 %>% 
  group_by(FULL.NAME) %>% 
  complete(YEAR = seq(YEAR[1], 2021, by = 1),
           MONTH = month(1:12, label = T)) %>% 
  mutate(YEAR.MONTH = paste(YEAR, MONTH)) %>% 
  fill(SP.NO) %>% 
  arrange(YEAR, MONTH, FULL.NAME)

data4 <- data3 %>% 
  group_by(YEAR.MONTH) %>% 
  slice_max(order_by = SP.NO, n = 10) %>% 
  mutate(RANK = row_number()) %>% 
  ungroup() %>% 
  arrange(YEAR.MONTH)

data5 <- data4 %>% 
  filter(YEAR > 2015)



plot <- ggplot(data5, aes(x = RANK, group = FULL.NAME,
                           fill = as.factor(FULL.NAME), colour = as.factor(FULL.NAME))) +
  geom_tile(aes(y = SP.NO, height = SP.NO, width = 0.9), 
            alpha = 0.8, colour = NA) +
  
  # text in x-axis (requires clip = "off" in coord_*)
  # paste() hack for spacing, as hjust > 1 causes weird artifacts in text spacing
  geom_text(aes(y = 0, label = paste(FULL.NAME, " ")), vjust = 0.2, hjust = 1) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_x_reverse() +
  
  # scale_y_continuous(labels = scales::comma) +
  guides(color = "none", fill = "none") +
  labs(title = "GKVK Campus: Top 10 eBirders by species",
       subtitle = "{closest_state}", 
       x = "", y = "Number of species observed") +
  theme(plot.title = element_text(size = 22),
        plot.subtitle = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),  # These relate to the axes post-flip
        axis.text.y  = element_blank(),  # These relate to the axes post-flip
        plot.margin = margin(1, 1, 1, 4, "cm")) +

  transition_states(YEAR.MONTH) +
  ease_aes("linear")

animate(plot, fps = 25, duration = 30, width = 800, height = 600)

```

```{r}


load("content/project/GKVK leaderboard/data_GKVK.RData")

data0 <- data_GKVK  %>% 
  mutate(CATEGORY == case_when(CATEGORY == "domestic" & 
                                 COMMON.NAME == "Rock Pigeon" ~ "species",
                               TRUE ~ CATEGORY)) %>% 
  filter(CATEGORY %in% c("issf","species")) %>% 
  select(OBSERVER.ID, OBSERVATION.DATE, YEAR, MONTH, DAY.M, COMMON.NAME) %>% 
  left_join(eBird.users) %>% 
  arrange(OBSERVATION.DATE, OBSERVER.ID) %>% 
  filter(FULL.NAME != "MigrantWatch (group account)")

data1 <- data0 %>% 
  group_by(OBSERVER.ID, COMMON.NAME) %>% 
  slice(1) %>% 
  arrange(OBSERVATION.DATE, OBSERVER.ID)

data2 <- data1 %>% 
  group_by(OBSERVER.ID) %>% 
  mutate(SP.NO = seq(n())) %>% 
  group_by(OBSERVER.ID, FULL.NAME, OBSERVATION.DATE) %>% 
  summarise(SP.NO = max(SP.NO))

data3 <- data2 %>% 
  group_by(OBSERVER.ID, FULL.NAME) %>% 
  complete(OBSERVATION.DATE = seq(OBSERVATION.DATE[1], as_date("2021-12-31"), by = 1)) %>% 
  fill(SP.NO) %>% 
  arrange(OBSERVATION.DATE, OBSERVER.ID)

data4 <- data3 %>% 
  group_by(OBSERVATION.DATE) %>% 
  slice_max(order_by = SP.NO, n = 10) %>% 
  mutate(YEAR = year(as.Date(OBSERVATION.DATE)),
         MONTH = month(as.Date(OBSERVATION.DATE), label = T),
         YEAR.MONTH = paste(YEAR, MONTH),
         RANK = row_number()) %>% 
  ungroup() %>% 
  arrange(OBSERVATION.DATE)

data5 <- data4 %>% 
  filter(YEAR > 2015)

x <- data3 %>% filter(FULL.NAME== "Karthik Thrikkadeeri")


plot1 <- ggplot(data4, aes(x = RANK, group = FULL.NAME,
                           fill = as.factor(FULL.NAME), colour = as.factor(FULL.NAME))) +
  geom_tile(aes(y = SP.NO, height = SP.NO, width = 0.9), 
            alpha = 0.8, colour = NA) +
  
  # text in x-axis (requires clip = "off" in coord_*)
  # paste() hack for spacing, as hjust > 1 causes weird artifacts in text spacing
  geom_text(aes(y = 0, label = paste(FULL.NAME, " ")), vjust = 0.2, hjust = 1) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_x_reverse() +
  
  # scale_y_continuous(labels = scales::comma) +
  guides(color = "none", fill = "none") +
  labs(title = "GKVK Campus: Top 10 eBirders by species",
       subtitle = "{closest_state}", 
       x = "", y = "Number of species observed") +
  theme(plot.title = element_text(size = 22),
        plot.subtitle = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),  # These relate to the axes post-flip
        axis.text.y  = element_blank(),  # These relate to the axes post-flip
        plot.margin = margin(1, 1, 1, 4, "cm")) +

  transition_states(OBSERVATION.DATE) +
  ease_aes("linear")

animate(plot1, fps = 50, duration = 30, width = 800, height = 600)

```

